FROM node:latest as build

COPY . /frontend

WORKDIR /frontend

RUN npm install

RUN npm install react-router-dom


RUN npm run build

FROM nginx:latest

COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf


COPY --from=build /frontend/build /usr/share/nginx/html


EXPOSE 80

EXPOSE 443

